data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql/data
    - /usr/local/taiga/media
    - /usr/local/taiga/static
    - /usr/local/taiga/logs
postgres:
  image: postgres
  environment:
    POSTGRES_USER: taiga
    POSTGRES_PASSWORD: password
  volumes_from:
    - data
taigaback:
  image: moss/taiga-back
  hostname: dev.example.com
  environment:
    SECRET_KEY: examplesecretkey
    EMAIL_USE_TLS: 'True'
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: youremail@gmail.com
    EMAIL_HOST_PASSWORD: yourpassword
    LDAP_ENABLED: 'True'
    LDAP_SERVER: "ldap://openldap"
    LDAP_PORT: 389
    LDAP_BIND_DN: "cn=admin,dc=example,dc=com"
    LDAP_BIND_PASSWORD: 'securepassword'
    LDAP_SEARCH_BASE: "ou=people,cn=admin,dc=example,dc=com"
    LDAP_FULL_NAME_PROPERTY: 'cn'
  links:
    - postgres:postgres
  volumes_from:
    - data
taigafront:
  image: moss/taiga-front-dist
  hostname: dev.example.com
  links:
    - taigaback
  environment:
    LDAP_ENABLED: 'True'
  volumes_from:
    - data
  ports:
    - 0.0.0.0:80:80
